server:
  port: 8082

spring:
  application:
    name: inventory

  datasource:
    url: jdbc:mysql://localhost:3306/eshop?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validation-query: select 'x' from dual

#  redis:
#    cluster:
#      nodes:
#        - 192.168.0.110:7001
#        - 192.168.0.111:7003
#        - 192.168.0.112:7005
#        - 192.168.0.112:7006
#

#mybatis相关配置
mybatis:
  type-aliases-package: com.young.eshop.inventory.model
  mapper-locations: classpath:com/young/eshop/inventory/mapper/mapping/*Mapper.xml


#log记录
logging:
  path: /var/log/young/${spring.application.name}
  level:
    com.young: DEBUG
    org.springframework.boot.actuate.endpoint: WARN
    org.springframework.web.servlet.mvc.method.annotation: WARN

