spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.0.113:3306/eshop?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: eshop
    password: eshop
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validation-query: select 'x' from dual


  redis:
    cluster:
      nodes:
        - 192.168.0.110:7001
        - 192.168.0.111:7003
        - 192.168.0.112:7005
        - 192.168.0.112:7006
    timeout: 5000
